# Generated by Django 5.1.15 on 2026-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_receipt_code_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В наличии'),
        ),
    ]
